

--Size of the window
WINDOW_WIDTH = 360
WINDOW_HEIGHT = 780
res = 40

--Size being emulated with push
VIRTUAL_WIDTH = 400
VIRTUAL_HEIGHT = 610

--FLAG CONSTANTS
FLAG_SCROLL = -150
GAP_WIDTH = 80
FLAG_SPEED = 100
FLAG_WIDTH = 30
FLAG_HEIGHT = 30

--SKIER CONSTANTS
SKIER_SPEED = 250
SKIER_WIDTH = 30
SKIER_HEIGHT = 30
ACCELERATION_SPEED = 95

--COUNTDOWN STATE
COUNTDOWN_TIME = 0.75

--LEVEL MAKING CONSTANTS
TILE_SIZE = 16 --16px
-- width and height of screen in tiles
SCREEN_TILE_WIDTH = VIRTUAL_WIDTH / TILE_SIZE
SCREEN_TILE_HEIGHT = VIRTUAL_HEIGHT / TILE_SIZE

--TILE ID
TILE_ID_EMPTY = 5
TILE_ID_EDGE = 3

--TILES THAT TRIGGER A COLLISION
COLLIDABLE_TILES = {
    TITLE_ID_EDGE
}